/**
 * SalesTim API
 * The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalesTimApi);
  }
}(this, function(expect, SalesTimApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalesTimApi.TeamsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TeamsApi', function() {
    describe('addTeamMember', function() {
      it('should call addTeamMember successfully', function(done) {
        //uncomment below and update the code to test addTeamMember
        //instance.addTeamMember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('archiveTeam', function() {
      it('should call archiveTeam successfully', function(done) {
        //uncomment below and update the code to test archiveTeam
        //instance.archiveTeam(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createTeamChannel', function() {
      it('should call createTeamChannel successfully', function(done) {
        //uncomment below and update the code to test createTeamChannel
        //instance.createTeamChannel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createTeamChannelTab', function() {
      it('should call createTeamChannelTab successfully', function(done) {
        //uncomment below and update the code to test createTeamChannelTab
        //instance.createTeamChannelTab(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createTeamProvisioningJob', function() {
      it('should call createTeamProvisioningJob successfully', function(done) {
        //uncomment below and update the code to test createTeamProvisioningJob
        //instance.createTeamProvisioningJob(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTeam', function() {
      it('should call deleteTeam successfully', function(done) {
        //uncomment below and update the code to test deleteTeam
        //instance.deleteTeam(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTeam', function() {
      it('should call getTeam successfully', function(done) {
        //uncomment below and update the code to test getTeam
        //instance.getTeam(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTeamChannelTabs', function() {
      it('should call getTeamChannelTabs successfully', function(done) {
        //uncomment below and update the code to test getTeamChannelTabs
        //instance.getTeamChannelTabs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTeamChannels', function() {
      it('should call getTeamChannels successfully', function(done) {
        //uncomment below and update the code to test getTeamChannels
        //instance.getTeamChannels(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTeamPrimaryChannel', function() {
      it('should call getTeamPrimaryChannel successfully', function(done) {
        //uncomment below and update the code to test getTeamPrimaryChannel
        //instance.getTeamPrimaryChannel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('unarchiveTeam', function() {
      it('should call unarchiveTeam successfully', function(done) {
        //uncomment below and update the code to test unarchiveTeam
        //instance.unarchiveTeam(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTeam', function() {
      it('should call updateTeam successfully', function(done) {
        //uncomment below and update the code to test updateTeam
        //instance.updateTeam(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
