/**
 * SalesTim API
 * The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalesTimApi);
  }
}(this, function(expect, SalesTimApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalesTimApi.CatalogTemplateNewTeam();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CatalogTemplateNewTeam', function() {
    it('should create an instance of CatalogTemplateNewTeam', function() {
      // uncomment below and update the code to test CatalogTemplateNewTeam
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be.a(SalesTimApi.CatalogTemplateNewTeam);
    });

    it('should have the property namingConventionWithTags (base name: "namingConventionWithTags")', function() {
      // uncomment below and update the code to test the property namingConventionWithTags
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property emailConventionWithTags (base name: "emailConventionWithTags")', function() {
      // uncomment below and update the code to test the property emailConventionWithTags
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property descriptionConventionWithTags (base name: "descriptionConventionWithTags")', function() {
      // uncomment below and update the code to test the property descriptionConventionWithTags
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property welcomeMessageConventionWithTags (base name: "welcomeMessageConventionWithTags")', function() {
      // uncomment below and update the code to test the property welcomeMessageConventionWithTags
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property namingConvention (base name: "namingConvention")', function() {
      // uncomment below and update the code to test the property namingConvention
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property emailConvention (base name: "emailConvention")', function() {
      // uncomment below and update the code to test the property emailConvention
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property descriptionConvention (base name: "descriptionConvention")', function() {
      // uncomment below and update the code to test the property descriptionConvention
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property welcomeMessageConvention (base name: "welcomeMessageConvention")', function() {
      // uncomment below and update the code to test the property welcomeMessageConvention
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property defaultName (base name: "defaultName")', function() {
      // uncomment below and update the code to test the property defaultName
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property defaultDescription (base name: "defaultDescription")', function() {
      // uncomment below and update the code to test the property defaultDescription
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property defaultWelcomeMessage (base name: "defaultWelcomeMessage")', function() {
      // uncomment below and update the code to test the property defaultWelcomeMessage
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property teamPrivacy (base name: "teamPrivacy")', function() {
      // uncomment below and update the code to test the property teamPrivacy
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

    it('should have the property addRequesterAsTeamOwner (base name: "addRequesterAsTeamOwner")', function() {
      // uncomment below and update the code to test the property addRequesterAsTeamOwner
      //var instance = new SalesTimApi.CatalogTemplateNewTeam();
      //expect(instance).to.be();
    });

  });

}));
