/**
 * SalesTim API
 * The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://docs.nbold.co/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiError from '../model/ApiError';
import AuditTrailRecords from '../model/AuditTrailRecords';
import AuditTrails from '../model/AuditTrails';

/**
* AuditTrails service.
* @module api/AuditTrailsApi
* @version 1.2.3
*/
export default class AuditTrailsApi {

    /**
    * Constructs a new AuditTrailsApi. 
    * @alias module:api/AuditTrailsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAuditTrailRecords operation.
     * @callback module:api/AuditTrailsApi~getAuditTrailRecordsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AuditTrailRecords} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all the records from an audit trail
     * Get all the records from an audit trail. TIER 2 | ROLES - AUTHORIZED_APP, COMPLIANCE_MANAGER, TEAMS_SERVICE_ADMIN, GLOBAL_ADMIN.
     * @param {String} code The audit trail code.
     * @param {module:api/AuditTrailsApi~getAuditTrailRecordsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AuditTrailRecords}
     */
    getAuditTrailRecords(code, callback) {
      let postBody = null;
      // verify the required parameter 'code' is set
      if (code === undefined || code === null) {
        throw new Error("Missing the required parameter 'code' when calling getAuditTrailRecords");
      }

      let pathParams = {
        'code': code
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AuditTrailRecords;
      return this.apiClient.callApi(
        '/audittrails/{code}/records', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAuditTrails operation.
     * @callback module:api/AuditTrailsApi~getAuditTrailsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AuditTrails} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get audit trails
     * Get all the audit trails accessible in your organization. TIER 3 | ROLES - AUTHORIZED_APP, COMPLIANCE_MANAGER, TEAMS_SERVICE_ADMIN, GLOBAL_ADMIN.
     * @param {module:api/AuditTrailsApi~getAuditTrailsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AuditTrails}
     */
    getAuditTrails(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AuditTrails;
      return this.apiClient.callApi(
        '/audittrails', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
