/**
 * SalesTim API
 * The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://docs.nbold.co/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiErrorErrorInnerError model module.
 * @module model/ApiErrorErrorInnerError
 * @version 1.2.3
 */
class ApiErrorErrorInnerError {
    /**
     * Constructs a new <code>ApiErrorErrorInnerError</code>.
     * JSON representation of the inner error (If available)
     * @alias module:model/ApiErrorErrorInnerError
     */
    constructor() { 
        
        ApiErrorErrorInnerError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiErrorErrorInnerError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiErrorErrorInnerError} obj Optional instance to populate.
     * @return {module:model/ApiErrorErrorInnerError} The populated <code>ApiErrorErrorInnerError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiErrorErrorInnerError();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('request-id')) {
                obj['request-id'] = ApiClient.convertToType(data['request-id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Inner error date
 * @member {Date} date
 */
ApiErrorErrorInnerError.prototype['date'] = undefined;

/**
 * Server-side generated unique request identifier
 * @member {String} request-id
 */
ApiErrorErrorInnerError.prototype['request-id'] = undefined;






export default ApiErrorErrorInnerError;

