/**
 * SalesTim API
 * The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CatalogTemplateNewTeam model module.
 * @module model/CatalogTemplateNewTeam
 * @version 1.2.3
 */
class CatalogTemplateNewTeam {
    /**
     * Constructs a new <code>CatalogTemplateNewTeam</code>.
     * Properties of the new team that will be created by the provisioning job.
     * @alias module:model/CatalogTemplateNewTeam
     */
    constructor() { 
        
        CatalogTemplateNewTeam.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CatalogTemplateNewTeam</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CatalogTemplateNewTeam} obj Optional instance to populate.
     * @return {module:model/CatalogTemplateNewTeam} The populated <code>CatalogTemplateNewTeam</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CatalogTemplateNewTeam();

            if (data.hasOwnProperty('namingConventionWithTags')) {
                obj['namingConventionWithTags'] = ApiClient.convertToType(data['namingConventionWithTags'], 'String');
            }
            if (data.hasOwnProperty('emailConventionWithTags')) {
                obj['emailConventionWithTags'] = ApiClient.convertToType(data['emailConventionWithTags'], 'String');
            }
            if (data.hasOwnProperty('descriptionConventionWithTags')) {
                obj['descriptionConventionWithTags'] = ApiClient.convertToType(data['descriptionConventionWithTags'], 'String');
            }
            if (data.hasOwnProperty('welcomeMessageConventionWithTags')) {
                obj['welcomeMessageConventionWithTags'] = ApiClient.convertToType(data['welcomeMessageConventionWithTags'], 'String');
            }
            if (data.hasOwnProperty('namingConvention')) {
                obj['namingConvention'] = ApiClient.convertToType(data['namingConvention'], 'String');
            }
            if (data.hasOwnProperty('emailConvention')) {
                obj['emailConvention'] = ApiClient.convertToType(data['emailConvention'], 'String');
            }
            if (data.hasOwnProperty('descriptionConvention')) {
                obj['descriptionConvention'] = ApiClient.convertToType(data['descriptionConvention'], 'String');
            }
            if (data.hasOwnProperty('welcomeMessageConvention')) {
                obj['welcomeMessageConvention'] = ApiClient.convertToType(data['welcomeMessageConvention'], 'String');
            }
            if (data.hasOwnProperty('defaultName')) {
                obj['defaultName'] = ApiClient.convertToType(data['defaultName'], 'String');
            }
            if (data.hasOwnProperty('defaultDescription')) {
                obj['defaultDescription'] = ApiClient.convertToType(data['defaultDescription'], 'String');
            }
            if (data.hasOwnProperty('defaultWelcomeMessage')) {
                obj['defaultWelcomeMessage'] = ApiClient.convertToType(data['defaultWelcomeMessage'], 'String');
            }
            if (data.hasOwnProperty('teamPrivacy')) {
                obj['teamPrivacy'] = ApiClient.convertToType(data['teamPrivacy'], 'String');
            }
            if (data.hasOwnProperty('addRequesterAsTeamOwner')) {
                obj['addRequesterAsTeamOwner'] = ApiClient.convertToType(data['addRequesterAsTeamOwner'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Defines the naming convention for the new team name (With the tags HTML representation).
 * @member {String} namingConventionWithTags
 */
CatalogTemplateNewTeam.prototype['namingConventionWithTags'] = undefined;

/**
 * Defines the naming convention for the email associated with the underlying group of the new team name (With the tags HTML representation).
 * @member {String} emailConventionWithTags
 */
CatalogTemplateNewTeam.prototype['emailConventionWithTags'] = undefined;

/**
 * Defines the naming convention for the new team description (With the tags HTML representation).
 * @member {String} descriptionConventionWithTags
 */
CatalogTemplateNewTeam.prototype['descriptionConventionWithTags'] = undefined;

/**
 * Defines the naming convention for the new team welcome message (With the tags HTML representation).
 * @member {String} welcomeMessageConventionWithTags
 */
CatalogTemplateNewTeam.prototype['welcomeMessageConventionWithTags'] = undefined;

/**
 * Defines the naming convention for the new team name (Without the tags HTML representation).
 * @member {String} namingConvention
 */
CatalogTemplateNewTeam.prototype['namingConvention'] = undefined;

/**
 * Defines the naming convention for the email associated with the underlying group of the new team name (Without the tags HTML representation).
 * @member {String} emailConvention
 */
CatalogTemplateNewTeam.prototype['emailConvention'] = undefined;

/**
 * Defines the naming convention for the new team description (Without the tags HTML representation).
 * @member {String} descriptionConvention
 */
CatalogTemplateNewTeam.prototype['descriptionConvention'] = undefined;

/**
 * Defines the naming convention for the new team welcome message (Without the tags HTML representation).
 * @member {String} welcomeMessageConvention
 */
CatalogTemplateNewTeam.prototype['welcomeMessageConvention'] = undefined;

/**
 * Defines the default team name presented to end-users in the new team provisioning form.
 * @member {String} defaultName
 */
CatalogTemplateNewTeam.prototype['defaultName'] = undefined;

/**
 * Defines the default team description presented to end-users in the new team provisioning form.
 * @member {String} defaultDescription
 */
CatalogTemplateNewTeam.prototype['defaultDescription'] = undefined;

/**
 * Defines the default team welcome message presented to end-users in the new team provisioning form.
 * @member {String} defaultWelcomeMessage
 */
CatalogTemplateNewTeam.prototype['defaultWelcomeMessage'] = undefined;

/**
 * Defines the new team privacy level.
 * @member {module:model/CatalogTemplateNewTeam.TeamPrivacyEnum} teamPrivacy
 */
CatalogTemplateNewTeam.prototype['teamPrivacy'] = undefined;

/**
 * Defines if the requester of the new team should be invited as a team owner or just as a team member.
 * @member {String} addRequesterAsTeamOwner
 */
CatalogTemplateNewTeam.prototype['addRequesterAsTeamOwner'] = undefined;





/**
 * Allowed values for the <code>teamPrivacy</code> property.
 * @enum {String}
 * @readonly
 */
CatalogTemplateNewTeam['TeamPrivacyEnum'] = {

    /**
     * value: "public"
     * @const
     */
    "public": "public",

    /**
     * value: "private"
     * @const
     */
    "private": "private",

    /**
     * value: "unknownFutureValue"
     * @const
     */
    "unknownFutureValue": "unknownFutureValue"
};



export default CatalogTemplateNewTeam;

