/**
 * SalesTim API
 * The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://docs.nbold.co/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CatalogTemplateTemplateConfigurationAudienceTargeting model module.
 * @module model/CatalogTemplateTemplateConfigurationAudienceTargeting
 * @version 1.2.3
 */
class CatalogTemplateTemplateConfigurationAudienceTargeting {
    /**
     * Constructs a new <code>CatalogTemplateTemplateConfigurationAudienceTargeting</code>.
     * The template audience targeting policy.
     * @alias module:model/CatalogTemplateTemplateConfigurationAudienceTargeting
     */
    constructor() { 
        
        CatalogTemplateTemplateConfigurationAudienceTargeting.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CatalogTemplateTemplateConfigurationAudienceTargeting</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CatalogTemplateTemplateConfigurationAudienceTargeting} obj Optional instance to populate.
     * @return {module:model/CatalogTemplateTemplateConfigurationAudienceTargeting} The populated <code>CatalogTemplateTemplateConfigurationAudienceTargeting</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CatalogTemplateTemplateConfigurationAudienceTargeting();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'String');
            }
            if (data.hasOwnProperty('rulesWithTags')) {
                obj['rulesWithTags'] = ApiClient.convertToType(data['rulesWithTags'], 'String');
            }
            if (data.hasOwnProperty('rules')) {
                obj['rules'] = ApiClient.convertToType(data['rules'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Defines if the template should be restricted to specific audiences or not.
 * @member {String} enabled
 */
CatalogTemplateTemplateConfigurationAudienceTargeting.prototype['enabled'] = undefined;

/**
 * Defines the audience targeting rules (With the tags HTML representation).
 * @member {String} rulesWithTags
 */
CatalogTemplateTemplateConfigurationAudienceTargeting.prototype['rulesWithTags'] = undefined;

/**
 * Defines the audience targeting rules (Without the tags HTML representation).
 * @member {String} rules
 */
CatalogTemplateTemplateConfigurationAudienceTargeting.prototype['rules'] = undefined;






export default CatalogTemplateTemplateConfigurationAudienceTargeting;

