/**
 * SalesTim API
 * The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApprovedApprovalResponsePayloadApprover from './ApprovedApprovalResponsePayloadApprover';

/**
 * The RejectedApprovalResponsePayload model module.
 * @module model/RejectedApprovalResponsePayload
 * @version 1.2.3
 */
class RejectedApprovalResponsePayload {
    /**
     * Constructs a new <code>RejectedApprovalResponsePayload</code>.
     * A negative approval response payload.
     * @alias module:model/RejectedApprovalResponsePayload
     */
    constructor() { 
        
        RejectedApprovalResponsePayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RejectedApprovalResponsePayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RejectedApprovalResponsePayload} obj Optional instance to populate.
     * @return {module:model/RejectedApprovalResponsePayload} The populated <code>RejectedApprovalResponsePayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RejectedApprovalResponsePayload();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('approver')) {
                obj['approver'] = ApprovedApprovalResponsePayloadApprover.constructFromObject(data['approver']);
            }
        }
        return obj;
    }


}

/**
 * Approval response message
 * @member {String} message
 */
RejectedApprovalResponsePayload.prototype['message'] = undefined;

/**
 * @member {module:model/ApprovedApprovalResponsePayloadApprover} approver
 */
RejectedApprovalResponsePayload.prototype['approver'] = undefined;






export default RejectedApprovalResponsePayload;

