/**
 * SalesTim API
 * The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@salestim.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MemberUserIdentifier from './MemberUserIdentifier';
import OwnerUserIdentifier from './OwnerUserIdentifier';

/**
 * The TeamProvisioningRequestTeamMembership model module.
 * @module model/TeamProvisioningRequestTeamMembership
 * @version 1.2.3
 */
class TeamProvisioningRequestTeamMembership {
    /**
     * Constructs a new <code>TeamProvisioningRequestTeamMembership</code>.
     * Requested members and owners of the team to be provisioned
     * @alias module:model/TeamProvisioningRequestTeamMembership
     */
    constructor() { 
        
        TeamProvisioningRequestTeamMembership.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamProvisioningRequestTeamMembership</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamProvisioningRequestTeamMembership} obj Optional instance to populate.
     * @return {module:model/TeamProvisioningRequestTeamMembership} The populated <code>TeamProvisioningRequestTeamMembership</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamProvisioningRequestTeamMembership();

            if (data.hasOwnProperty('members')) {
                obj['members'] = ApiClient.convertToType(data['members'], [MemberUserIdentifier]);
            }
            if (data.hasOwnProperty('owners')) {
                obj['owners'] = ApiClient.convertToType(data['owners'], [OwnerUserIdentifier]);
            }
        }
        return obj;
    }


}

/**
 * An array of UserIdentifier. See [https://developers.salestim.com/api/reference/Models/UserIdentifier](https://developers.salestim.com/api/reference/Models/UserIdentifier) for more information.
 * @member {Array.<module:model/MemberUserIdentifier>} members
 */
TeamProvisioningRequestTeamMembership.prototype['members'] = undefined;

/**
 * An array of UserIdentifier. See [https://developers.salestim.com/api/reference/Models/UserIdentifier](https://developers.salestim.com/api/reference/Models/UserIdentifier) for more information.
 * @member {Array.<module:model/OwnerUserIdentifier>} owners
 */
TeamProvisioningRequestTeamMembership.prototype['owners'] = undefined;






export default TeamProvisioningRequestTeamMembership;

