/**
 * nBold API
 * Visit our [API documentation](https://docs.nbold.co/api/) for more information. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TeamProvisioningRequestTeamMembership from './TeamProvisioningRequestTeamMembership';

/**
 * The TeamProvisioningRequestTeam model module.
 * @module model/TeamProvisioningRequestTeam
 * @version 2.0.0
 */
class TeamProvisioningRequestTeam {
    /**
     * Constructs a new <code>TeamProvisioningRequestTeam</code>.
     * Properties of the team to be created
     * @alias module:model/TeamProvisioningRequestTeam
     * @param name {String} Requested team name
     */
    constructor(name) { 
        
        TeamProvisioningRequestTeam.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>TeamProvisioningRequestTeam</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamProvisioningRequestTeam} obj Optional instance to populate.
     * @return {module:model/TeamProvisioningRequestTeam} The populated <code>TeamProvisioningRequestTeam</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamProvisioningRequestTeam();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('welcomeMessage')) {
                obj['welcomeMessage'] = ApiClient.convertToType(data['welcomeMessage'], 'String');
            }
            if (data.hasOwnProperty('membership')) {
                obj['membership'] = TeamProvisioningRequestTeamMembership.constructFromObject(data['membership']);
            }
        }
        return obj;
    }


}

/**
 * Requested team name
 * @member {String} name
 */
TeamProvisioningRequestTeam.prototype['name'] = undefined;

/**
 * Requested team description
 * @member {String} description
 */
TeamProvisioningRequestTeam.prototype['description'] = undefined;

/**
 * Requested team welcome message
 * @member {String} welcomeMessage
 */
TeamProvisioningRequestTeam.prototype['welcomeMessage'] = undefined;

/**
 * @member {module:model/TeamProvisioningRequestTeamMembership} membership
 */
TeamProvisioningRequestTeam.prototype['membership'] = undefined;






export default TeamProvisioningRequestTeam;

