/**
 * nBold API
 * Visit our [API documentation](https://docs.nbold.co/api/) for more information. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApiErrorErrorInnerError from './ApiErrorErrorInnerError';

/**
 * The ApiErrorError model module.
 * @module model/ApiErrorError
 * @version 2.0.0
 */
class ApiErrorError {
    /**
     * Constructs a new <code>ApiErrorError</code>.
     * JSON representation of the error
     * @alias module:model/ApiErrorError
     */
    constructor() { 
        
        ApiErrorError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiErrorError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiErrorError} obj Optional instance to populate.
     * @return {module:model/ApiErrorError} The populated <code>ApiErrorError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiErrorError();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('innerError')) {
                obj['innerError'] = ApiErrorErrorInnerError.constructFromObject(data['innerError']);
            }
        }
        return obj;
    }


}

/**
 * The HTTP error code
 * @member {String} code
 */
ApiErrorError.prototype['code'] = undefined;

/**
 * The error message
 * @member {String} message
 */
ApiErrorError.prototype['message'] = undefined;

/**
 * @member {module:model/ApiErrorErrorInnerError} innerError
 */
ApiErrorError.prototype['innerError'] = undefined;






export default ApiErrorError;

