/**
 * nBold API
 * Visit our [API documentation](https://docs.nbold.co/api/) for more information. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CatalogTemplate from './CatalogTemplate';

/**
 * The CatalogTemplates model module.
 * @module model/CatalogTemplates
 * @version 2.0.0
 */
class CatalogTemplates {
    /**
     * Constructs a new <code>CatalogTemplates</code>.
     * A collection of templates from your corporate catalog. See [https://docs.nbold.co/api/reference/Models/CatalogTemplate](https://docs.nbold.co/api/reference/Models/CatalogTemplate) for more information.
     * @alias module:model/CatalogTemplates
     */
    constructor() { 
        
        CatalogTemplates.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CatalogTemplates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CatalogTemplates} obj Optional instance to populate.
     * @return {module:model/CatalogTemplates} The populated <code>CatalogTemplates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CatalogTemplates();

            if (data.hasOwnProperty('@odata.context')) {
                obj['@odata.context'] = ApiClient.convertToType(data['@odata.context'], 'String');
            }
            if (data.hasOwnProperty('@odata.count')) {
                obj['@odata.count'] = ApiClient.convertToType(data['@odata.count'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], [CatalogTemplate]);
            }
        }
        return obj;
    }


}

/**
 * Odata context
 * @member {String} @odata.context
 */
CatalogTemplates.prototype['@odata.context'] = undefined;

/**
 * Number of templates in the collection
 * @member {Number} @odata.count
 */
CatalogTemplates.prototype['@odata.count'] = undefined;

/**
 * Array of catalog templates
 * @member {Array.<module:model/CatalogTemplate>} value
 */
CatalogTemplates.prototype['value'] = undefined;






export default CatalogTemplates;

