/**
 * nBold API
 * Visit our [API documentation](https://docs.nbold.co/api/get-started) for more information. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HookSignatureRequest model module.
 * @module model/HookSignatureRequest
 * @version 2.0.0
 */
class HookSignatureRequest {
    /**
     * Constructs a new <code>HookSignatureRequest</code>.
     * A HookSignatureRequest object comprised of the secret and payload.
     * @alias module:model/HookSignatureRequest
     * @param secret {String} Webhook secret
     * @param payload {Object} Webhook payload
     */
    constructor(secret, payload) { 
        
        HookSignatureRequest.initialize(this, secret, payload);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, secret, payload) { 
        obj['secret'] = secret;
        obj['payload'] = payload;
    }

    /**
     * Constructs a <code>HookSignatureRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HookSignatureRequest} obj Optional instance to populate.
     * @return {module:model/HookSignatureRequest} The populated <code>HookSignatureRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HookSignatureRequest();

            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], Object);
            }
        }
        return obj;
    }


}

/**
 * Webhook secret
 * @member {String} secret
 */
HookSignatureRequest.prototype['secret'] = undefined;

/**
 * Webhook payload
 * @member {Object} payload
 */
HookSignatureRequest.prototype['payload'] = undefined;






export default HookSignatureRequest;

