/**
 * nBold API
 * Visit our [API documentation](https://docs.nbold.co/api/get-started) for more information. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetadataQueryResult model module.
 * @module model/MetadataQueryResult
 * @version 2.0.0
 */
class MetadataQueryResult {
    /**
     * Constructs a new <code>MetadataQueryResult</code>.
     * ResultsMetadata for a collaboration process artefact.
     * @alias module:model/MetadataQueryResult
     */
    constructor() { 
        
        MetadataQueryResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetadataQueryResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetadataQueryResult} obj Optional instance to populate.
     * @return {module:model/MetadataQueryResult} The populated <code>MetadataQueryResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetadataQueryResult();

            if (data.hasOwnProperty('artefact_type')) {
                obj['artefact_type'] = ApiClient.convertToType(data['artefact_type'], 'String');
            }
            if (data.hasOwnProperty('artefact_id')) {
                obj['artefact_id'] = ApiClient.convertToType(data['artefact_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Artefact type (Among \"MicrosoftTeamsTeam\", \"MicrosoftTeamsChannel\", \"MicrosoftTeamsConversation\")
 * @member {String} artefact_type
 */
MetadataQueryResult.prototype['artefact_type'] = undefined;

/**
 * Artefact ID
 * @member {String} artefact_id
 */
MetadataQueryResult.prototype['artefact_id'] = undefined;






export default MetadataQueryResult;

