/**
 * nBold API
 * Visit our [API documentation](https://docs.nbold.co/api/get-started) for more information. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PermanentMember from './PermanentMember';

/**
 * The PermanentMembership model module.
 * @module model/PermanentMembership
 * @version 2.0.0
 */
class PermanentMembership {
    /**
     * Constructs a new <code>PermanentMembership</code>.
     * Owners and members of permanent membership settings.
     * @alias module:model/PermanentMembership
     */
    constructor() { 
        
        PermanentMembership.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PermanentMembership</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermanentMembership} obj Optional instance to populate.
     * @return {module:model/PermanentMembership} The populated <code>PermanentMembership</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermanentMembership();

            if (data.hasOwnProperty('members')) {
                obj['members'] = ApiClient.convertToType(data['members'], [PermanentMember]);
            }
            if (data.hasOwnProperty('owners')) {
                obj['owners'] = ApiClient.convertToType(data['owners'], [PermanentMember]);
            }
        }
        return obj;
    }


}

/**
 * Members of a permanent membership team, as an array of PermanentMember. See [https://docs.nbold.co/api/latest/reference/Models/PermanentMember](https://docs.nbold.co/api/latest/reference/Models/PermanentMember) for more information.
 * @member {Array.<module:model/PermanentMember>} members
 */
PermanentMembership.prototype['members'] = undefined;

/**
 * Members of a permanent membership team, as an array of PermanentMember. See [https://docs.nbold.co/api/latest/reference/Models/PermanentMember](https://docs.nbold.co/api/latest/reference/Models/PermanentMember) for more information.
 * @member {Array.<module:model/PermanentMember>} owners
 */
PermanentMembership.prototype['owners'] = undefined;






export default PermanentMembership;

