/**
 * nBold API
 * Visit our [API documentation](https://docs.nbold.co/api/) for more information. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReportsCategory model module.
 * @module model/ReportsCategory
 * @version 2.0.0
 */
class ReportsCategory {
    /**
     * Constructs a new <code>ReportsCategory</code>.
     * A category of reports.
     * @alias module:model/ReportsCategory
     */
    constructor() { 
        
        ReportsCategory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportsCategory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportsCategory} obj Optional instance to populate.
     * @return {module:model/ReportsCategory} The populated <code>ReportsCategory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportsCategory();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Reports category ID
 * @member {String} id
 */
ReportsCategory.prototype['id'] = undefined;

/**
 * Reports category title
 * @member {String} title
 */
ReportsCategory.prototype['title'] = undefined;

/**
 * Reports category description
 * @member {String} description
 */
ReportsCategory.prototype['description'] = undefined;






export default ReportsCategory;

