/**
 * nBold API
 * Visit our [API documentation](https://docs.nbold.co/api/get-started) for more information. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Report model module.
 * @module model/Report
 * @version 2.0.0
 */
class Report {
    /**
     * Constructs a new <code>Report</code>.
     * A report.
     * @alias module:model/Report
     */
    constructor() { 
        
        Report.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Report</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Report} obj Optional instance to populate.
     * @return {module:model/Report} The populated <code>Report</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Report();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('logo')) {
                obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], ['String']);
            }
            if (data.hasOwnProperty('category_id')) {
                obj['category_id'] = ApiClient.convertToType(data['category_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Report ID
 * @member {String} id
 */
Report.prototype['id'] = undefined;

/**
 * Report type (dashboard / question)
 * @member {String} type
 */
Report.prototype['type'] = undefined;

/**
 * Report title
 * @member {String} title
 */
Report.prototype['title'] = undefined;

/**
 * Report description
 * @member {String} description
 */
Report.prototype['description'] = undefined;

/**
 * Report logo
 * @member {String} logo
 */
Report.prototype['logo'] = undefined;

/**
 * Report parameters (tenant_id / user_id)
 * @member {Array.<String>} parameters
 */
Report.prototype['parameters'] = undefined;

/**
 * Report category ID
 * @member {String} category_id
 */
Report.prototype['category_id'] = undefined;






export default Report;

