/**
 * nBold API
 * Visit our [API documentation](https://docs.nbold.co/api/get-started) for more information. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TeamMemberSettings model module.
 * @module model/TeamMemberSettings
 * @version 2.0.0
 */
class TeamMemberSettings {
    /**
     * Constructs a new <code>TeamMemberSettings</code>.
     * @alias module:model/TeamMemberSettings
     */
    constructor() { 
        
        TeamMemberSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamMemberSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamMemberSettings} obj Optional instance to populate.
     * @return {module:model/TeamMemberSettings} The populated <code>TeamMemberSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamMemberSettings();

            if (data.hasOwnProperty('allowCreateUpdateChannels')) {
                obj['allowCreateUpdateChannels'] = ApiClient.convertToType(data['allowCreateUpdateChannels'], 'Boolean');
            }
            if (data.hasOwnProperty('allowCreatePrivateChannels')) {
                obj['allowCreatePrivateChannels'] = ApiClient.convertToType(data['allowCreatePrivateChannels'], 'Boolean');
            }
            if (data.hasOwnProperty('allowDeleteChannels')) {
                obj['allowDeleteChannels'] = ApiClient.convertToType(data['allowDeleteChannels'], 'Boolean');
            }
            if (data.hasOwnProperty('allowAddRemoveApps')) {
                obj['allowAddRemoveApps'] = ApiClient.convertToType(data['allowAddRemoveApps'], 'Boolean');
            }
            if (data.hasOwnProperty('allowCreateUpdateRemoveTabs')) {
                obj['allowCreateUpdateRemoveTabs'] = ApiClient.convertToType(data['allowCreateUpdateRemoveTabs'], 'Boolean');
            }
            if (data.hasOwnProperty('allowCreateUpdateRemoveConnectors')) {
                obj['allowCreateUpdateRemoveConnectors'] = ApiClient.convertToType(data['allowCreateUpdateRemoveConnectors'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Allow create update channels
 * @member {Boolean} allowCreateUpdateChannels
 */
TeamMemberSettings.prototype['allowCreateUpdateChannels'] = undefined;

/**
 * Allow create private channels
 * @member {Boolean} allowCreatePrivateChannels
 */
TeamMemberSettings.prototype['allowCreatePrivateChannels'] = undefined;

/**
 * Allow delete channels
 * @member {Boolean} allowDeleteChannels
 */
TeamMemberSettings.prototype['allowDeleteChannels'] = undefined;

/**
 * Allow add/remove apps
 * @member {Boolean} allowAddRemoveApps
 */
TeamMemberSettings.prototype['allowAddRemoveApps'] = undefined;

/**
 * Allow create/remove tabs
 * @member {Boolean} allowCreateUpdateRemoveTabs
 */
TeamMemberSettings.prototype['allowCreateUpdateRemoveTabs'] = undefined;

/**
 * Allow create/remove connectors
 * @member {Boolean} allowCreateUpdateRemoveConnectors
 */
TeamMemberSettings.prototype['allowCreateUpdateRemoveConnectors'] = undefined;






export default TeamMemberSettings;

