/**
 * nBold API
 * Visit our [API documentation](https://docs.nbold.co/api/) for more information. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@nbold.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TeamGuestSettings model module.
 * @module model/TeamGuestSettings
 * @version 2.0.0
 */
class TeamGuestSettings {
    /**
     * Constructs a new <code>TeamGuestSettings</code>.
     * @alias module:model/TeamGuestSettings
     */
    constructor() { 
        
        TeamGuestSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamGuestSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamGuestSettings} obj Optional instance to populate.
     * @return {module:model/TeamGuestSettings} The populated <code>TeamGuestSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamGuestSettings();

            if (data.hasOwnProperty('allowCreateUpdateChannels')) {
                obj['allowCreateUpdateChannels'] = ApiClient.convertToType(data['allowCreateUpdateChannels'], 'Boolean');
            }
            if (data.hasOwnProperty('allowDeleteChannels')) {
                obj['allowDeleteChannels'] = ApiClient.convertToType(data['allowDeleteChannels'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Allow create/update channels by guests
 * @member {Boolean} allowCreateUpdateChannels
 */
TeamGuestSettings.prototype['allowCreateUpdateChannels'] = undefined;

/**
 * Allow delete channels by guests
 * @member {Boolean} allowDeleteChannels
 */
TeamGuestSettings.prototype['allowDeleteChannels'] = undefined;






export default TeamGuestSettings;

