name: Generate docs website and deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-publish-assets:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Generate assets
        run: |
          bun run build

      # See: https://github.com/marketplace/actions/git-commit-push-action
      - name: Publish assets
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          email: ${{ github.actor }}@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: Updated public assets
          target_branch: published
          force: true
