# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Docs-prd

on:
  push:
    branches:
      - new-docx
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: nbold.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_0D0F978E313649D9BE62F10D1B179FE5 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_90F0ED1266AE4AC6965FC9D6F3258503 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: nbold.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_0D0F978E313649D9BE62F10D1B179FE5 }}/nbold/nbold/docs:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CEB2CB72B9BB48AE8682CAA0653BEEC6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_55A22A4714AA465480D6961D96E5F902 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FDDA671BF7834A83BC92D2928B459390 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Docs-prd'
          slot-name: 'Production'
          images: 'nbold.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_0D0F978E313649D9BE62F10D1B179FE5 }}/nbold/nbold/docs:${{ github.sha }}'
          